In [2]:
import numpy as np 


In [3]:
#Practice attempt#
np.random.rand(4,2)

array([[0.61383548, 0.9731114 ],
       [0.86072167, 0.1660495 ],
       [0.5877461 , 0.36417617],
       [0.46028897, 0.52011088]])

In [4]:
#Practice attempt creating 4 by 3#
np.random.randint(0,501, size = (4,3))

array([[125, 404, 254],
       [322, 243, 412],
       [227,  26, 490],
       [467, 378,  59]])

In [46]:
#Creates randomly generate array sized 10x50 with 1 to 500#
x= np.random.randint(1,501, size = (10,50))
print(x)

[[308 320 324  54 360 483 366 235 477 326 183  86 240 275 483 126 255 231
  415 318 426 301 468 165   8  41 467   3 251   2 260  36 161 453 360  58
  424 383 301 282 146 242 236  15 296 342 271 223 253 462]
 [118 396 318 353 260 133 400  45 118 250  76 359 396 183 190 355 386  80
  482 410 358 491  18 462 350 231 116 257 434 301 257  90 403 415 445 167
   77 483 248 325 319 114  38  17 426 248  35 140 331 105]
 [ 96 409  82 439 122  51 393 222 253  57  83 229 475  69 327 328 190 216
    1 314 446 368  78 332 446 392 365 395  56 272  88 336 167 351 446 144
   93 448 136 319 173 386 497 233 421 122 186 206  65 261]
 [151 194 456  70 226 344 492  60 466 480  60 159  20 303 254 436 306  84
  179 366 221 413  34 262 297 108 376 279 440 498 285 387 202  17 483 323
  458 109 450 186  82 363 300 393 308 268 343 175 146 317]
 [365 498  55 495 454 131  95  44 340 227 424 496 161  12 373 101 384 478
  103 237 450 114 346 300 449   8 284  12  87 113 177 200 113  41  16 362
  128 393 325  17 343 29

In [47]:
#Provides sum of columns#
x.sum(axis=0)

array([2341, 2451, 2769, 2503, 2467, 1601, 2543, 1220, 2365, 2812, 2580,
       2643, 2385, 2245, 2761, 2703, 2656, 1740, 2983, 2747, 3278, 2969,
       2025, 3100, 2877, 2287, 2749, 2117, 2006, 2527, 1996, 2493, 2857,
       2538, 2495, 2937, 2557, 2964, 2284, 2504, 2278, 3272, 2901, 2017,
       2708, 2151, 2880, 1610, 2555, 2367])

In [48]:
#Provides sum of rows#

x.sum(axis=1)

array([13201, 13009, 12584, 13629, 11842, 11024, 11203, 12866, 12922,
       12534])

In [49]:
#Provides sum#
x.sum()

124814

In [50]:
#Provides min#
x.min()

1

In [51]:
#Provides max#
x.max()

500

In [52]:
#Provides mean#
x.mean()

249.628

In [53]:
#Provides standard deviation#
x.std()

149.67430512950443

In [54]:
#Sorts overall by columns#
np.sort(x, axis=0)

array([[ 96,  21,  55,  54,  60,   7,  11,  15,  33,   2,  60,   7,  20,
         12,  14,  15,  79,  29,   1,  12,  73,  27,   2,  21,   8,   8,
         38,   3,   4,   2,  52,  36, 113,  17,   2,  58,  77,  13,  34,
         17,  82, 114,  37,  15,  33,  31,  35,  39,  14,  67],
       [118,  37,  82,  70, 122,  18,  32,  44,  84,  57,  76,  86,  89,
         14,  71, 101, 105,  75, 103, 195, 123, 114,  18, 158,  55,  41,
         46,  12,  56, 113,  88,  58, 161,  41,  16, 144,  93,  79,  37,
        119, 146, 242,  38,  17,  65,  36, 186,  60,  65, 105],
       [118,  72, 118,  70, 142,  21,  95,  45, 118, 227,  83, 159, 154,
         69, 190, 120, 140,  80, 179, 196, 221, 126,  34, 165,  58,  73,
        116,  59,  87, 161, 141,  90, 165,  41,  96, 167, 128,  83,  43,
        167, 158, 290, 217,  26,  68, 122, 198,  79, 134, 110],
       [118, 101, 188, 172, 193,  51, 163,  57, 139, 232, 169, 229, 159,
        183, 190, 126, 190,  84, 280, 237, 265, 283,  78, 262, 297, 108,
     

In [55]:
#Sorts overall by rows#
np.sort(x, axis=1)

array([[  2,   3,   8,  15,  36,  41,  54,  58,  86, 126, 146, 161, 165,
        183, 223, 231, 235, 236, 240, 242, 251, 253, 255, 260, 271, 275,
        282, 296, 301, 301, 308, 318, 320, 324, 326, 342, 360, 360, 366,
        383, 415, 424, 426, 453, 462, 467, 468, 477, 483, 483],
       [ 17,  18,  35,  38,  45,  76,  77,  80,  90, 105, 114, 116, 118,
        118, 133, 140, 167, 183, 190, 231, 248, 248, 250, 257, 257, 260,
        301, 318, 319, 325, 331, 350, 353, 355, 358, 359, 386, 396, 396,
        400, 403, 410, 415, 426, 434, 445, 462, 482, 483, 491],
       [  1,  51,  56,  57,  65,  69,  78,  82,  83,  88,  93,  96, 122,
        122, 136, 144, 167, 173, 186, 190, 206, 216, 222, 229, 233, 253,
        261, 272, 314, 319, 327, 328, 332, 336, 351, 365, 368, 386, 392,
        393, 395, 409, 421, 439, 446, 446, 446, 448, 475, 497],
       [ 17,  20,  34,  60,  60,  70,  82,  84, 108, 109, 146, 151, 159,
        175, 179, 186, 194, 202, 221, 226, 254, 262, 268, 279, 285, 297,
     

In [56]:
#Sorts columns by 2#
sortedcol = x[x[:,1].argsort()]
sortedcol


array([[325,  21, 188, 237, 400, 168,  32, 168, 268, 345, 468, 304, 210,
        462,  71,  15, 421, 307, 450, 279, 265,  27, 421, 490,  55, 374,
        332, 330, 109, 302, 258, 416, 367, 480, 126, 460, 287,  79,  34,
        332, 158, 318, 391,  26,  33,  36, 332,  39, 408, 110],
       [118,  37, 420, 172, 250,  18, 163, 176, 187, 444, 346,   7, 159,
         14,  14, 421,  79, 104, 390, 420, 457, 489, 263, 454, 363, 473,
        271, 233, 284, 424, 141, 107, 165, 350, 303, 295, 282, 489,  43,
        416, 210, 321, 463, 109, 119, 329, 365, 123, 370, 216],
       [455,  72, 475, 290, 142,   7, 359,  15,  33, 449, 382, 260, 481,
        417, 190, 306, 105, 136, 280, 196,  73, 126, 102, 456,  58, 116,
         38, 210,   4, 161,  52, 432, 454,  41,   2, 229, 183,  13, 399,
        341, 453, 497, 281, 266,  65,  31, 336, 250, 134, 350],
       [118, 101, 118, 323,  60, 245, 232, 198, 139,   2, 169, 290, 154,
        304, 482, 120, 390,  29, 291,  12, 123, 283, 293,  21, 351, 471,
     

In [57]:
#Sorts rows by 2#
sortedrow = x[:, x[1].argsort()]
sortedrow

array([[ 15, 468, 271, 236, 235, 183, 424, 231,  36, 462, 242, 467, 308,
        477, 483, 223,  58, 275, 483,  41, 301, 342, 326,   3, 260, 360,
          2, 324, 146, 282, 253,   8,  54, 126, 426,  86, 255, 320, 240,
        366, 161, 318, 453, 296, 251, 360, 165, 415, 383, 301],
       [ 17,  18,  35,  38,  45,  76,  77,  80,  90, 105, 114, 116, 118,
        118, 133, 140, 167, 183, 190, 231, 248, 248, 250, 257, 257, 260,
        301, 318, 319, 325, 331, 350, 353, 355, 358, 359, 386, 396, 396,
        400, 403, 410, 415, 426, 434, 445, 462, 482, 483, 491],
       [233,  78, 186, 497, 222,  83,  93, 216, 336, 261, 386, 365,  96,
        253,  51, 206, 144,  69, 327, 392, 136, 122,  57, 395,  88, 122,
        272,  82, 173, 319,  65, 446, 439, 328, 446, 229, 190, 409, 475,
        393, 167, 314, 351, 421,  56, 446, 332,   1, 448, 368],
       [393,  34, 343, 300,  60,  60, 458,  84, 387, 317, 363, 376, 151,
        466, 344, 175, 323, 303, 254, 108, 450, 268, 480, 279, 285, 226,
     